trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

container: 
  # image: aldmarj/ado_container:redirect_err
  image: aldmarj/ado_container:no_start
  options: --name container_logs #--attach STDOUT

steps:
- script:
      curl localhost:3000/process &&
      cat /app/stderr.log &&
      curl localhost:3000/memory &&
      cat /app/stdout.log


      # echo "howdy"
      # touch logfiles.txt 
      # echo "+++++++LOGFILES+++++++" > logfiles.txt
      # && 2>&1 | tee -a logfiles.txt
      # tail -f logfiles.txt

      
# - task: CmdLine@2
#   inputs:
#     script: docker logs container_logs
