pool:
  vmImage: 'ubuntu-latest'

container: 
  image: ubuntu:18.04
  options: --name container_logs

steps:
- script: echo "howdy" #&& touch logfiles.txt && 2>&1 | tee -a logfiles.txt && tail -f logfiles.txt

- task: CmdLine@2
  inputs:
    script: docker logs container_logs