trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

container: 
  image: aldmarj/ado_container:starts_up
  options: --name container_logs --attach STDOUT

steps:
- script: 
      echo "howdy"
      touch logfiles.txt && 2>&1 | tee -a logfiles.txt
      curl localhost:3000/process
      curl localhost:3000/memory
      tail -f logfiles.txt

# - task: CmdLine@2
#   inputs:
#     script: docker logs container_logs