name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: aldmarj/ado_container:ghactions-txt
    steps:
      - name: ls 
        shell: bash
        run: ls -ltra /app

      - name: whoami
        shell: bash
        run: whoami

      - name: cat STDOUT
        shell: bash
        run: cat /app/stdout.txt

      - name: cat STDERR
        shell: bash
        run: more /app/stderr.log

      - name: cp stderr
        shell: bash
        run: cp /app/stderr.log /app/read-stderr.log

      - name: cat read-stderr
        shell: bash
        run: cat /app/read-stderr.log

      - name: cat STARTUP.SH
        shell: bash
        run: cat /app/startup.sh

        
     
