name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: aldmarj/ado_container:ghactions
      env:
        NODE_ENV: development
      ports:
        - 80
      # volumes:
      #   - /app:/app
      options: --cpus 1
    steps:
      - name: ls 
        shell: bash
        run: ls -ltra /app

      - name: whoami
        shell: bash
        run: whoami

      - name: cat STDOUT
        shell: sh
        run: cat /app/stdout.log

      - name: cat STDERR
        shell: bash
        run: cat /app/startup.sh

        
     
