name: CI
on:
  push:
    branches: [ master ]
defaults:
  run:
    shell: bash
jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: aldmarj/ado_container:ghactions-nosleep
      options: --name nosleep-crash
    steps:
      - name: ls 
        shell: bash
        run: ls -ltra /app

      - name: whoami
        shell: bash
        run: whoami

      - name: cat STDERR
        shell: bash
        run: cat /app/stderr.log

      - name: cat STARTUP.SH
        shell: bash
        run: cat /app/startup.sh

  vm-job:
    runs-on: ubuntu-latest

    steps:
     - name: docker ps
       shell: bash
       run: docker ps -a

     - name: docker logs
       shell: bash
       run: docker logs nosleep-crash

     
