name: CI
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: aldmarj/ado_container:no_start_sleep
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - /app:/app
      options: --cpus 1
    steps:
      - name: npm install app
        run: npm install
